import "@/app/globals.css";

import { Inter } from 'next/font/google'
import Header from '@/components/header'

export const metadata = {
  title: "Pizzería",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (

    <html lang="es">
      <body className={`antialiased min-h-screen`} >
        <Header />
            {children}
      </body>
    </html>
  
);
}
